import { Eta } from "eta";
// list of options: https://eta.js.org/docs/api/configuration
const eta = new Eta({ useWith: true });

export function render(
  fileName: string,
  template: string,
  otherPrompts: Array<
    { target: string; renderedPrompt?: string; imageUrl?: string }
  >,
): string {
  // function throws, if dependencies are not yet available or template is invalid

  // ideas:
  // - light/dark mode
  // - weather
  // - news headline
  // - current song
  // - moon phase
  // - random art style (e.g. impressionism, cubism, surrealism, etc.)
  // - random architecture style (e.g. brutalism, etc.)
  // - random art epoche (e.g. renaissance, baroque, etc.)
  // - random midjourney look (e.g. octane render)
  // - random artist (e.g. picasso, etc.)
  // - random designer (e.g. dieter rams, etc.)
  // - random human emotion
  // - random facial expression
  // - gpt
  // - gpt generated categories, like `randomColors`

  console.log(`rendering fileName '${fileName}': '${template}'`);
  const rendered = eta.renderString(template, {
    promptFrom: (
      fileName: string,
      transform: (original: string) => string = (x) => x,
    ) => {
      // , transform?: (string) => string
      // let transform = (x) => x;
      // this might crash and signal to the caller that the prompt dependencies does not exist (yet)
      console.log(
        `  looking for renderedPrompt from '${fileName}'...`,
      );
      const found: string | undefined = (otherPrompts.find((prompt) =>
        prompt.fileName == fileName && prompt.renderedPrompt != undefined
      ))?.renderedPrompt;
      if (!found) {
        throw new Error(`could not find renderedPrompt from '${fileName}'`);
      }
      return transform(found);
    },
    imageFrom: (
      fileName: string,
    ) => {
      // , transform?: (string) => string
      // let transform = (x) => x;
      // this might crash and signal to the caller that the prompt dependencies does not exist (yet)
      console.log(
        `  looking for imageUrl from '${fileName}'...`,
      );
      const found: string | undefined = (otherPrompts.find((prompt) =>
        prompt.fileName == fileName && prompt.imageUrl != undefined
      ))?.imageUrl;
      if (!found) {
        throw new Error(`could not find imageUrl from '${fileName}'`);
      }
      return found;
    },
    random: randomElement,
    season: season(new Date().getMonth()),
    dayOfWeek: new Date().toLocaleString("default", { weekday: "long" }),
    monthCEST: new Date().toLocaleString("default", {
      month: "long",
      timeZone: "Europe/Paris",
    }),
    dayOfWeekCEST: new Date().toLocaleString("default", {
      weekday: "long",
      timeZone: "Europe/Paris",
    }),
    dayPeriodCEST: dayPeriod(new Date().getUTCHours() + 2),
    timeOfDayCEST: new Date().getUTCHours() + 2,
    colors: [
      "Alizarin Red",
      "Amber Yellow",
      "Amethyst Purple",
      "Apricot Orange",
      "Aqua Blue",
      "Aquamarine Blue",
      "Azure Blue",
      "Beige Neutral",
      "Bisque Light Orange",
      "Black",
      "Blue",
      "Blush Pink",
      "Bronze Brown",
      "Brown",
      "Burgundy Red",
      "Byzantium Purple",
      "Carmine Red",
      "Cerulean Blue",
      "Champagne Light Yellow",
      "Charcoal Gray",
      "Chartreuse Green",
      "Chocolate Brown",
      "Cobalt Blue",
      "Copper Brown",
      "Coral Pink",
      "Cornflower Blue",
      "Crimson Red",
      "Cyan Blue",
      "Emerald Green",
      "Fuchsia Pink",
      "Gold Yellow",
      "Gray",
      "Green",
      "Harlequin Green",
      "Indigo Blue",
      "Ivory White",
      "Jade Green",
      "Lavender Purple",
      "Lemon Yellow",
      "Lilac Light Purple",
      "Lime Green",
      "Magenta",
      "Maroon Red",
      "Mauve Pale Purple",
      "Navy Blue",
      "Ochre Yellow",
      "Olive Green",
      "Orange",
      "Orchid Purple",
      "Peach Orange",
      "Pearl White",
      "Periwinkle Blue",
      "Pink",
      "Plum Purple",
      "Puce Dark Pink",
      "Purple",
      "Raspberry Red",
      "Red",
      "Rose Red",
      "Ruby Red",
      "Salmon Pink",
      "Sapphire Blue",
      "Scarlet Red",
      "Silver Gray",
      "Sky Blue",
      "Slate Gray",
      "Tan Brown",
      "Taupe Brown",
      "Teal Blue-Green",
      "Turquoise Blue",
      "Ultramarine Blue",
      "Violet Purple",
      "Viridian Green",
      "White",
      "Yellow",
      "Zinc Gray",
      "Mint Green",
      "Cherry Red",
      "Cinnabar Red",
      "Citrine Yellow",
      "Cream White",
      "Eggplant Purple",
      "Flame Red-Orange",
      "Honeydew Light Green",
      "Khaki Brown",
      "Lime Green",
      "Mango Orange",
      "Melon Light Orange",
      "Mustard Yellow",
      "Myrtle Green",
      "Nectarine Orange",
      "Olive Drab Green",
      "Papaya Orange",
      "Pistachio Green",
      "Rust Brown",
      "Saffron Yellow",
      "Sangria Red",
      "Slate Blue",
      "Slate Gray",
      "Snow White",
      "Steel Blue",
      "Straw Yellow",
      "Sunset Orange-Red",
      "Tangerine Orange",
      "Thistle Light Purple",
      "Tomato Red",
      "Vanilla Cream White",
      "Wheat Light Brown",
      "Yam Orange",
      "Zaffre Blue",
    ],
    animals: [
      "Albatross",
      "Alligator",
      "Anteater",
      "Antelope",
      "Armadillo",
      "Badger",
      "Bat",
      "Bear",
      "Beaver",
      "Bison",
      "Boar",
      "Buffalo",
      "Camel",
      "Cat",
      "Centipede",
      "Chameleon",
      "Cheetah",
      "Chicken",
      "Chimpanzee",
      "Clam",
      "Cormorant",
      "Cow",
      "Crab",
      "Crane",
      "Crocodile",
      "Crow",
      "Deer",
      "Dingo",
      "Dog",
      "Dolphin",
      "Donkey",
      "Dove",
      "Duck",
      "Eagle",
      "Echidna",
      "Eel",
      "Elephant",
      "Emu",
      "Falcon",
      "Ferret",
      "Fish",
      "Flamingo",
      "Fox",
      "Frog",
      "Gazelle",
      "Gecko",
      "Gerbil",
      "Giraffe",
      "Gnu",
      "Goat",
      "Goose",
      "Guinea pig",
      "Guinea Pig",
      "Hamster",
      "Hare",
      "Hawk",
      "Hedgehog",
      "Heron",
      "Hippopotamus",
      "Horse",
      "Hummingbird",
      "Hyena",
      "Iguana",
      "Impala",
      "Jaguar",
      "Jaguarundi",
      "Jellyfish",
      "Kangaroo",
      "Kitten",
      "Kiwi",
      "Koala",
      "Komodo Dragon",
      "Lemur",
      "Leopard",
      "Lion",
      "Lizard",
      "Llama",
      "Lobster",
      "Lynx",
      "Marmoset",
      "Marten",
      "Meerkat",
      "Millipede",
      "Mink",
      "Mole",
      "Monkey",
      "Moose",
      "Mouse",
      "Narwhal",
      "Newt",
      "Octopus",
      "Ostrich",
      "Otter",
      "Owl",
      "Oyster",
      "Panda",
      "Panther",
      "Parrot",
      "Peacock",
      "Pelican",
      "Penguin",
      "Pig",
      "Pigeon",
      "Platypus",
      "Porcupine",
      "Puffin",
      "Quail",
      "Quetzal",
      "Rabbit",
      "Raccoon",
      "Rat",
      "Raven",
      "Rhea",
      "Rhinoceros",
      "Salamander",
      "Scallop",
      "Scorpion",
      "Seagull",
      "Seal",
      "Sea Urchin",
      "Shark",
      "Sheep",
      "Shrimp",
      "Skunk",
      "Sloth",
      "Snail",
      "Snake",
      "Sparrow",
      "Spider",
      "Squid",
      "Squirrel",
      "Starfish",
      "Stork",
      "Swan",
      "Tapir",
      "Tarantula",
      "Tasmanian Devil",
      "Tiger",
      "Toad",
      "Tortoise",
      "Toucan",
      "Turkey",
      "Turtle",
      "Urchin",
      "Vicuna",
      "Vulture",
      "Wallaby",
      "Walrus",
      "Weasel",
      "Whale",
      "Wolf",
      "Wombat",
      "Woodpecker",
      "Yak",
      "Zebra",
      "Zebu",
    ],
    insects: [
      "Ant",
      "Bee",
      "Butterfly",
      "Caterpillar",
      "Cockroach",
      "Cricket",
      "Dragonfly",
      "Fly",
      "Grasshopper",
      "Ladybug",
      "Mantis",
      "Moth",
      "Mosquito",
      "Beetle",
      "Termite",
      "Wasp",
      "Bedbug",
      "Firefly",
      "Hornet",
      "Cicada",
      "Gnat",
      "June Bug",
      "Locust",
      "Spider",
      "Earwig",
      "Stink Bug",
      "Praying Mantis",
      "Centipede",
      "Millipede",
      "Tarantula",
      "Scorpion",
      "Daddy Longlegs",
      "Bumblebee",
    ],
    musicalInstruments: [
      "Accordion",
      "Bagpipes",
      "Balalaika",
      "Banjo",
      "Bass Guitar",
      "Bassoon",
      "Bongo",
      "Bouzouki",
      "Cello",
      "Clarinet",
      "Conga",
      "Didgeridoo",
      "Djembe",
      "Double Bass",
      "Drums",
      "Electric Guitar",
      "English Horn",
      "Erhu",
      "Euphonium",
      "Flute",
      "French Horn",
      "Guitar",
      "Guqin",
      "Harmonica",
      "Harp",
      "Harpsichord",
      "Keytar",
      "Koto",
      "Mandolin",
      "Marimba",
      "Oboe",
      "Organ",
      "Percussion",
      "Piano",
      "Piccolo",
      "Santoor",
      "Sarod",
      "Saxophone",
      "Sitar",
      "Synthesizer",
      "Tabla",
      "Theremin",
      "Timpani",
      "Trombone",
      "Trumpet",
      "Tuba",
      "Ukulele",
      "Veena",
      "Vibraphone",
      "Violin",
      "Xylophone",
    ],
    artStyles: [
      "Abstract Art",
      "Art Nouveau Style",
      "Baroque Style",
      "Bauhaus Style",
      "Byzantine Art",
      "Cubism",
      "Dada Art Movement",
      "Expressionism Art",
      "Fauvism",
      "Futurism Art Movement",
      "Gothic Art",
      "Graffiti Art",
      "Impressionism Art",
      "Japonism Art",
      "Kinetic Art",
      "Minimalism Art",
      "Modernism Art",
      "Naive Art (Primitivism)",
      "Neoclassicism Art",
      "Neo-Expressionism Art",
      "Op Art",
      "Pop Art",
      "Post-Impressionism Art",
      "Realism Art",
      "Renaissance Art",
      "Rococo Art",
      "Romanticism Art",
      "Surrealism",
      "Symbolism Art",
      "Tonalism",
      "Ukiyo-e",
      "Art Deco Style",
      "Conceptual Art",
      "Constructivism Art",
      "Art Brut (Raw Art)",
      "Pointillism",
      "Social Realism Art",
      "Suprematism",
      "Tachisme",
      "Photorealism",
      "Pre-Raphaelite Art",
      "Street Art",
      "Superflat Art",
      "Trompe-l'œil Art",
      "Arte Povera",
      "Digital Art",
      "Stuckism",
      "Romanesque Art",
      "Ancient Greek Art",
      "Ancient Roman Art",
      "Medieval Art",
      "Asian Art",
      "Islamic Art",
      "African Art",
      "Aboriginal Art",
      "Native American Art",
      "Oceanic Art",
    ],
    fruits: [
      "apple",
      "banana",
      "cherry",
      "date",
      "grape",
      "kiwi",
      "lemon",
      "mango",
      "orange",
      "peach",
      "pear",
      "plum",
      "pineapple",
      "raspberry",
      "strawberry",
      "watermelon",
      "blueberry",
      "blackberry",
      "grapefruit",
      "tangerine",
      "papaya",
      "melon",
      "apricot",
      "coconut",
      "lime",
    ],
    vegetables: [
      "carrot",
      "broccoli",
      "cauliflower",
      "pea",
      "green bean",
      "lettuce",
      "tomato",
      "potato",
      "onion",
      "bell pepper",
      "cabbage",
      "spinach",
      "kale",
      "zucchini",
      "cucumber",
      "corn",
      "asparagus",
      "celery",
      "eggplant",
      "garlic",
      "mushroom",
      "radish",
      "turnip",
      "beet",
      "brussels sprout",
    ],
    songTitles90s: [
      "Smells Like Teen Spirit",
      "Enter Sandman",
      "Wannabe",
      "No Rain",
      "Under the Bridge",
      "Don't Speak",
      "Black Hole Sun",
      "Killing Me Softly",
      "I Will Always Love You",
      "Losing My Religion",
      "Creep",
      "Unfinished Sympathy",
      "Bitter Sweet Symphony",
      "November Rain",
      "MMMBop",
      "Torn",
      "Black",
      "My Own Worst Enemy",
      "Baby One More Time",
      "I Want it That Way",
      "Waterfalls",
      "Don't Let Go (Love)",
      "California Love",
      "Ice Ice Baby",
      "Can't Touch This",
      "Gangsta's Paradise",
      "Wonderwall",
      "Song 2",
      "Vogue",
      "Jump Around",
      "Barbie Girl",
      "Tubthumping",
      "Macarena",
      "Smooth",
      "I'll Be Missing You",
      "All That She Wants",
      "Genie in a Bottle",
      "Summertime",
      "Karma Police",
      "...Baby One More Time",
      "The Sign",
      "Gotta Be",
      "My Own Worst Enemy",
      "Save Tonight",
      "Unbelievable",
      "I'll Make Love To You",
      "Whatta Man",
      "Mo Money Mo Problems",
      "It's All Coming Back to Me Now",
      "U Can't Touch This",
    ],
  });
  console.log(`  rendered: '${rendered}'`);
  return rendered;
}

function dayPeriod(hourUTC: number): string {
  if (hourUTC >= 5 && hourUTC <= 11) {
    return "morning";
  } else if (hourUTC >= 12 && hourUTC <= 13) {
    return "noon";
  } else if (hourUTC >= 14 && hourUTC <= 17) {
    return "afternoon";
  } else if (hourUTC >= 18 && hourUTC <= 21) {
    return "evening";
  } else {
    return "night";
  }
}

// generic function to return a random element from an array
function randomElement<T>(array: Array<T>): T {
  return array[Math.floor(Math.random() * array.length)];
}

function season(month: number): string {
  if (month >= 2 && month <= 4) {
    return "spring";
  } else if (month >= 5 && month <= 7) {
    return "summer";
  } else if (month >= 8 && month <= 10) {
    return "autumn";
  } else {
    return "winter";
  }
}
