name: Generate

on:
  workflow_dispatch:
  schedule:
    - cron: "45 3,9,15 * * *" # 15 minutes before the hour, 3 times a day (UTC)


jobs:
  generate:
    name: "Generate wallpapers"
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    timeout-minutes: 15
    concurrency:
      # never run jobs in parallel, don't cancel jobs
      group: "generate"
      cancel-in-progress: false
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "setup node and yarn"
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Install yq
        run: |
          curl --silent --location https://github.com/mikefarah/yq/releases/download/v4.12.0/yq_linux_amd64.tar.gz |\
          tar xz && sudo mv yq_linux_amd64 /usr/bin/yq

      - name: "Install node dependencies"
        run: yarn install --frozen-lockfile

      - name: "Generate wallpapers"
        run: |
          set -e
          npx tsx generate.ts
          rm -f wallpapers/.gitignore
          mogrify -format jpg -quality 95 wallpapers/*.png
          ls -la wallpapers
        env:
          SERVER_ID: ${{ secrets.SERVER_ID }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          SALAI_TOKEN: ${{ secrets.SALAI_TOKEN }}
          STABILITY_AI_API_KEY: ${{ secrets.STABILITY_AI_API_KEY }}

      - name: Generate cron timestamp
        run: |
          set -e
          CRONEXPR=$(yq '.on.schedule[0].cron' < .github/workflows/generate.yml)
          npx tsx listCeiledCronHours.ts "$CRONEXPR" > updateHoursUTC.json
          cat updateHoursUTC.json

      - name: Prepare upload
        run: |
          mkdir -p static/wallpapers
          cp updateHoursUTC.json static/updateHoursUTC.json
          cp -r wallpapers/*.jpg static/wallpapers/

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: static
          clean-exclude: static
