name: Generate

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  generate:
    name: "Generate wallpapers"
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    concurrency:
      # never run jobs in parallel, don't cancel jobs
      group: "generate"
      cancel-in-progress: false
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "setup node and yarn"
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: "Install dependencies"
        run: yarn install --frozen-lockfile

      - name: "Generate wallpapers"
        run: npx tsx generate.ts
        env:
          SERVER_ID: ${{ secrets.SERVER_ID }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          SALAI_TOKEN: ${{ secrets.SALAI_TOKEN }}

      - name: "Upload wallpapers"
        uses: actions/upload-artifact@v3
        with:
          name: wallpapers
          path: wallpapers/*.png
