name: Generate Wallpapers

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0,6,12,18 * * *" # one hour before the update (UTC)


jobs:
  generate:
    name: "Generate wallpapers"
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    timeout-minutes: 60
    concurrency:
      # never run jobs in parallel, don't cancel jobs
      group: "generate"
      cancel-in-progress: false
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "setup node and yarn"
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Install yq
        run: |
          curl --silent --location https://github.com/mikefarah/yq/releases/download/v4.35.1/yq_linux_amd64.tar.gz |\
          tar xz && sudo mv yq_linux_amd64 /usr/bin/yq

      - name: "Install node dependencies"
        run: yarn install --frozen-lockfile

      - name: "Generate wallpapers"
        run: |
          set -e
          # npx ts-node generate-wpp.ts
          npx tsx generate-wallpapers.ts
          convert wallpapers/wallpaper-mobile-latest.webp -blur 0x64 -modulate 100,150,100 wallpapers/wallpaper-mobile-homescreen-latest.webp
          rm -f wallpapers/.gitignore
          mogrify -format jpg -quality 95 wallpapers/*.webp
          ls -la wallpapers
        env:
          SERVER_ID: ${{ secrets.SERVER_ID }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          SALAI_TOKEN: ${{ secrets.SALAI_TOKEN }}
          STABILITY_AI_API_KEY: ${{ secrets.STABILITY_AI_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Generate cron timestamp
        run: |
          set -e
          CRONEXPR=$(yq '.on.schedule[0].cron' < .github/workflows/generate-wallpapers.yml)
          npx tsx ceiledCronExpression.ts "$CRONEXPR" > cronUTC
          npx tsx ceiledCronHours.ts "$CRONEXPR" > updateHoursUTC.json
          cat cronUTC updateHoursUTC.json

      - name: Prepare upload
        run: |
          set -e
          mkdir -p static/wallpapers
          cp updateHoursUTC.json cronUTC static/
          cp -r wallpapers/*-latest.jpg static/wallpapers/
          cp -r wallpapers/*.json static/wallpapers/
          find static

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: static
          clean: false # keep old files if not overridden
          single-commit: true # don't keep history
