name: Generate Recipe

on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * *"


jobs:
  generate:
    name: "Generate Recipe"
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    timeout-minutes: 60
    concurrency:
      # never run jobs in parallel, don't cancel jobs
      group: "generate"
      cancel-in-progress: false
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "setup node and yarn"
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: "Install node dependencies"
        run: yarn install --frozen-lockfile

      - name: "Generate recipes"
        run: |
          set -e
          npx ts-node generate-recipe.ts
          rm -f recipe/.gitignore
          mogrify -format jpg -quality 95 recipe/*.png
          ls -la recipe
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SERVER_ID: ${{ secrets.SERVER_ID }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          SALAI_TOKEN: ${{ secrets.SALAI_TOKEN }}
          STABILITY_AI_API_KEY: ${{ secrets.STABILITY_AI_API_KEY }}

      - name: Prepare upload
        run: |
          set -e
          mkdir -p static/recipe
          cp -r recipe/* static/recipe
          find static

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: static
          clean: false # keep old files if not overridden
          single-commit: true # don't keep history
